### ISSUE TITLE
Missing Values

### ISSUE THREAD

**Issue by mmznrSTAT** [openZH/mdd-ogd-handbook#20]
Vorschlag: lieber einfach leer lassen als NA. Bsp:

A,B,C
4,,5
2,3,4

("Standard" sagt meines Wissens nichts dazu: https://datatracker.ietf.org/doc/html/rfc4180#page-2)

**Comment by Lathei** [comment]
hinzufügen, dass Werte wie 9999 vermieden werden sollen, da diese schnell übersehen werden

**Comment by andreasamsler** [comment]
Danke für eure Feedbacks!

Vorschlag:
"Werte, die ausdrücklich unbekannt sind, weisen wir als `NA` aus. Ansonsten lassen wir die Zelle leer `4,,5`."

**Comment by andreasamsler** [comment]
in v1.0 übernommen
