### ISSUE TITLE
Pro Beobachtung eine Zeile

### ISSUE THREAD

**Issue by Lathei** [openZH/mdd-ogd-handbook#25]
anfügen, dass die oberste Zeile immer die Variablen Namen sind. Nur eine Zeile für alle Variablen Namen, kein Titel, kein Text. Zeilen sind:

1. Zeile = Variabel Namen
2. und alle weiteren Zeilen = Varabel Werte

**Comment by Lathei** [comment]
ah sorry, steht bereits hier:
Keine Spalten-Hierarchien, also keine miteinander zusammengeführten Zellen (z.B. um Ober- und Unterkategorien zu repräsentieren), sondern Oberkategorien in einer ersten Spalte, Unterkategorien in einer zweiten Spalte.
    Beispiel: https://www.zh.ch/de/politik-staat/opendata.html?keyword=ogd#/details/523@fachstelle-ogd-kanton-zuerich

fände ich aber passender bei den Zeilen.

**Comment by andreasamsler** [comment]
Entscheid: zw. "Vorgaben" und "Tabellarische Daten im Format CSV strukturieren wir gemäss dem Prinzip 'Tidy Data'." eine CSV-Beispiel mit `` einfügen

**Comment by andreasamsler** [comment]
![tidydata1](https://www.produnis.de/R/images/TidyData1.png)

**Comment by andreasamsler** [comment]
jahr,organisationseinheit,gesuche_haengig_jan,gesuche_total,zugang_uneingeschraenkt_gewaehrt
2013,Direktion der Justiz und des Innern,1,52,45
2013,Sicherheitsdirektion,,12,4
2013,Finanzdirektion,,14,14
2013,Volkswirtschaftsdirektion,,3,2
2013,Gesundheitsdirektion,1,45,8
2013,Bildungsdirektion,6,25,10
2013,Baudirektion,1,9,7
2013,Staatskanzlei,,,
2014,Direktion der Justiz und des Innern,11,31,19
2014,Sicherheitsdirektion,,21,11
2014,Finanzdirektion,,15,14
2014,Volkswirtschaftsdirektion,,32,31
2014,Gesundheitsdirektion,8,33,4
2014,Bildungsdirektion,4,24,7
2014,Baudirektion,1,7,8
2014,Staatskanzlei,,1,1

**Comment by andreasamsler** [comment]
in v1.0 übernommen
